/**
 * Stitch HTML uses Material Symbols Outlined (`data-icon` / glyph names).
 * Map those names to `react-native-vector-icons` MaterialIcons names.
 */
export const stitchIconMap = {
  arrow_back: 'arrow-back',
  close: 'close',
  menu: 'menu',
  search: 'search',
  tune: 'tune',
  map: 'map',
  list: 'list',
  favorite: 'favorite',
  favorite_border: 'favorite-border',
  share: 'share',
  call: 'call',
  mail: 'mail',
  visibility: 'visibility',
  visibility_off: 'visibility-off',
  person: 'person',
  settings: 'settings',
  notifications: 'notifications',
  receipt_long: 'receipt-long',
  explore: 'explore',
  store: 'store',
  shopping_bag: 'shopping-bag',
  payments: 'payment',
  help: 'help',
  eco: 'eco',
  check_circle: 'check-circle',
  error: 'error',
  chevron_right: 'chevron-right',
  chevron_left: 'chevron-left',
  add: 'add',
  remove: 'remove',
  filter_list: 'filter-list',
  location_on: 'location-on',
  schedule: 'schedule',
  local_offer: 'local-offer',
  info: 'info',
  grass: 'grass',
  water_drop: 'water-drop',
  egg: 'egg',
  nutrition: 'set-meal',
  local_fire_department: 'local-fire-department',
  credit_card: 'credit-card',
  attach_money: 'attach-money',
  qr_code_scanner: 'qr-code-scanner',
  storefront: 'storefront',
  star: 'star',
  star_border: 'star-border',
  arrow_downward: 'arrow-downward',
  check: 'check',
  check_circle_outline: 'check-circle-outline',
  logout: 'logout',
  manage_accounts: 'manage-accounts',
  support_agent: 'support-agent',
  account_balance_wallet: 'account-balance-wallet',
  photo_camera: 'photo-camera',
  image: 'image',
  attachment: 'attachment',
  edit: 'edit',
  expand_more: 'expand-more',
  expand_less: 'expand-less',
  lock: 'lock',
  delete: 'delete',
  chat: 'chat',
  shield: 'shield',
  shield_lock: 'shield',
  /** Stitch `your_environmental_impact` Phosphor → Material */
  wb_cloudy: 'wb-cloudy',
  directions_car: 'directions-car',
  smartphone: 'smartphone',
  park: 'park',
  wifi_off: 'wifi-off',
  refresh: 'refresh',
  ios_share: 'ios-share',
  /** Discover category chips (`standardized_discover_feed_*`) */
  restaurant: 'restaurant',
  bakery_dining: 'bakery-dining',
  local_cafe: 'local-cafe',
  lunch_dining: 'lunch-dining',
  local_pizza: 'local-pizza',
  local_grocery_store: 'local-grocery-store',
  egg_alt: 'egg-alt',
  local_shipping: 'local-shipping',
  arrow_forward: 'arrow-forward',
  home: 'home',
  list_alt: 'list-alt',
  local_mall: 'local-mall',
  inventory_2: 'inventory-2',
  monitoring: 'insights',
  bar_chart: 'bar-chart',
  dashboard: 'dashboard',
  add_circle: 'add-circle',
  /** Merchant onboarding / review (`merchant_onboarding_*`, `merchant_onboarding_4_4`) */
  corporate_fare: 'business',
  account_balance: 'account-balance',
  my_location: 'my-location',
  /** Merchant orders verification / handover */
  verified: 'verified',
  more_vert: 'more-vert',
  /** Create / edit rescue bag (`create_rescue_bag`, `edit_rescue_bag`) */
  category: 'category',
  sell: 'sell',
  publish: 'publish',
  add_photo_alternate: 'add-photo-alternate',
  preview: 'visibility',
  save: 'save',
  /** Merchant finance (`merchant_finance`) */
  percent: 'percent',
  trending_up: 'trending-up',
  event: 'event',
  download: 'file-download',
  history: 'history',
  calendar_month: 'calendar-today',
  group: 'group',
  more_horiz: 'more-horiz',
  gavel: 'gavel',
  alarm_on: 'alarm-on',
  analytics: 'analytics',
  /** Admin shells (audit logs / application review) */
  tag: 'label',
  smart_toy: 'smart-toy',
  warning: 'warning',
  block: 'block',
  account_balance_2: 'account-balance',
  /** Admin merchant detail (`admin_merchant_detail`) — identity + open complaints */
  badge: 'badge',
  flag: 'flag',
  /** Per-outlet editor + customer outlet detail */
  phone: 'phone',
  directions: 'directions',
  toggle_on: 'toggle-on',
  toggle_off: 'toggle-off',
  zoom_out_map: 'zoom-out-map',
  history_edu: 'history-edu',
  /** Admin platform configuration system status */
  cloud_done: 'cloud-done',
  cloud_off: 'cloud-off',
  /** Discover `Include sold out` toggle pill (`discover_sold_out_transition`) */
  remove_shopping_cart: 'remove-shopping-cart',
  /** Audit log row "more" affordance (`admin_audit_logs`) */
  data_object: 'data-object',
  /** Live monitor empty state (`live_merchant_monitor_rush_hour` "No customer waiting"). */
  person_outline: 'person-outline',
  /** KPI delta chips on `MerchantDashboard` (`standardized_merchant_dashboard_*`). */
  trending_down: 'trending-down',
  /**
   * Appearance row + Discover 2D/3D toggle (theme preference UI + map pitch flip).
   * Stitch references `palette` for the appearance affordance and `terrain` for the
   * pitched-camera toggle on the live map. `brightness_auto` / `dark_mode` /
   * `light_mode` are the trio used by the `ProfileTheme` picker rows;
   * `radio_button_*` render the selected/unselected affordance on each row.
   */
  palette: 'palette',
  brightness_auto: 'brightness-auto',
  dark_mode: 'dark-mode',
  light_mode: 'light-mode',
  radio_button_checked: 'radio-button-checked',
  radio_button_unchecked: 'radio-button-unchecked',
  terrain: 'terrain',
} as const;

export type StitchIconName = keyof typeof stitchIconMap;
